### ISSUE TITLE
Display deck matches on site

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#610] opened 2016-11-16 06:05 UTC
J_meka wanted to know who he'd played against in his league run, and I needed to do a SQL query to find out.

We should either add it to /deck/, or make a /matches/<deck_id>/ page.

**Comment by bakert** [comment] 2016-11-16 09:24
Dupe of #517

**Closed as completed by bakert** 2016-11-16 09:24 UTC
