### ISSUE TITLE
/tournaments/ is very squashed

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/Penny-Dreadful-Tools#3977] opened 2018-01-08 04:57 UTC
![screenshot-2018-1-8 tournaments pennydreadfulmagic com](https://user-images.githubusercontent.com/194254/34659402-7cfd2eb0-f48c-11e7-90f7-b946381b9352.png)

**Comment by bakert** [comment] 2018-01-08 19:27
We respect a readable line length as defined in Butterwick's Practical Typography and elsewhere. So that's why everything except the calendar is not stretching to fill. The calendar can be as wide as it wants but it's just stretching to fit all the content and it all fits in there.

So everything ends up fitting in that space on the left on this page in particular. There isn't quite enough space in your browser as you have it to fit two &lt;article&gt; side-by-side. I'm not sure if that would happen or not even if it were wider.

The fact that you logged this as an issue makes me want to think about the design though. We could have more left-margin on larger screens.

**Comment by bakert** [comment] 2018-01-08 19:27
That tiny search box looks terrible, though :D

**Comment by bakert** [comment] 2018-01-09 00:32
ad5b547 is the tiny text box on Firefox thing. It'll probably cause some other issue because the HTML/CSS we get from Google is horrendous but it seems to work.

I'm closing this as intended behavior but I'll try and think about how to use the space more in "article" pages.

**Closed as completed by bakert** 2018-01-09 00:32 UTC
