### ISSUE TITLE
Every discord command can be use by any person on the Discord.

### ISSUE THREAD

**Issue by kzcheng** [PennyDreadfulMTG/Penny-Dreadful-Tools#7620] opened 2020-08-10 02:19 UTC
The check for if a Discord User is admin does not work, so every Discord command can be used by anyone.

This currently includes the command `!restart` and `!rotate`.

**Comment by kzcheng** [comment] 2020-08-10 02:20
See #7505.

**Comment by kzcheng** [comment] 2020-08-10 02:21
It seems the line `@commands.check(commands.is_owner())` in `restartbot.py` and `rotate.py` does not function correctly.

**Comment by silasary** [comment] 2020-08-10 02:27
Duplicate of #7505

**Closed as completed by silasary** 2020-08-10 02:27 UTC
Labels: triage
