### ISSUE TITLE
Show all illegal cards in the pdm site deck checker

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/Penny-Dreadful-Tools#4715] opened 2018-04-29 02:44 UTC
Here's what it looks like currently 
![image](https://user-images.githubusercontent.com/31076829/39402721-7d689916-4b35-11e8-8748-73e2cf71982c.png)

Would be nice if it showed all illegal cards at once like the pdmtgo one
![image](https://user-images.githubusercontent.com/31076829/39402724-ab4d2f04-4b35-11e8-9bbb-5ab3eb1f1e4a.png)

**Comment by bakert** [comment] 2018-05-05 13:04
@jgabrielygalan

**Comment by bakert** [comment] 2018-05-05 23:27
Duplicate of #1488

**Closed as completed by bakert** 2018-05-05 23:27 UTC
Labels: + improvement

**Comment by BackAlleyG** [comment] 2018-05-25 01:33
@bakert this doesn't really seem like a duplicate, at least of the issue you linked. Related maybe but doesn't seem like a duplicate.

**Comment by silasary** [comment] 2018-05-25 01:40
They use the same backend.   The deck checker is literally just the league signup form, but without actually signing people up to the league.

**Comment by BackAlleyG** [comment] 2018-05-25 01:42
Ahh, I see. That makes sense.
