### ISSUE TITLE
500 error at /api/github (github_tools) list index out of range

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/Penny-Dreadful-Tools#6140] opened 2019-03-05 17:26 UTC
3 occurrences. Started 17 hours ago.

https://github.com/PennyDreadfulMTG/perf-reports/issues/42746

**Comment by bakert** [comment] 2019-03-05 17:26
```
500 error at /api/github

list index out of range

Reported on github_tools by logged_out

            --------------------------------------------------------------------------------
            Request Method: POST
            Path: /api/github?
            Cookies: {}
            Endpoint: /api/github
            View Args: {}
            Person: logged_out
            Referrer: None
            Request Data: {}
Host: localhost:5002
Accept-Encoding: gzip
Cf-Ipcountry: US
X-Forwarded-For: 192.30.252.39, 162.158.106.170
Cf-Ray: 4b27d4c91f0abb54-SEA
X-Forwarded-Proto: https
Cf-Visitor: {"scheme":"https"}
Accept: */*
User-Agent: GitHub-Hookshot/1174c8d
X-Github-Event: pull_request
X-Github-Delivery: 34a482a0-3eda-11e9-86e8-855beac00f8c
Content-Type: application/json
Cf-Connecting-Ip: 192.30.252.39
Cdn-Loop: cloudflare
X-Forwarded-Host: gh.pennydreadfulmagic.com

X-Forwarded-Server: gh.pennydreadfulmagic.com
Connection: Keep-Alive
Content-Length: 25300
IndexError
list index out of range
Stack Trace:

  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/discord/.local/lib/python3.6/site-packages/github_webhook/webhook.py", line 73, in _postreceive
    hook(data)
  File "./github_tools/__init__.py", line 48, in on_pull_request
    webhooks.check_for_changelogs(pr)
  File "./github_tools/webhooks.py", line 71, in check_for_changelogs
    lines = build_changelog(change)
  File "./github_tools/webhooks.py", line 89, in build_changelog
    oldversions[req.name] = req.specs[0][1]

Exception_hash: a3002f02109b60a0f38c2e56461fccb1a0a0b99e

Labels: github_tools; IndexError
```

**Comment by bakert** [comment] 2019-03-05 17:27
```
500 error at /api/github

list index out of range

Reported on github_tools by logged_out

            --------------------------------------------------------------------------------
            Request Method: POST
            Path: /api/github?
            Cookies: {}
            Endpoint: /api/github
            View Args: {}
            Person: logged_out
            Referrer: None
            Request Data: {}
Host: localhost:5002
Accept-Encoding: gzip
Cf-Ipcountry: US
X-Forwarded-For: 192.30.253.29, 162.158.106.170
Cf-Ray: 4b287969c8b6c9af-SEA
X-Forwarded-Proto: https
Cf-Visitor: {"scheme":"https"}
Accept: */*
User-Agent: GitHub-Hookshot/1174c8d
X-Github-Event: pull_request
X-Github-Delivery: e7d5ee90-3ee9-11e9-9725-5863a0c6e8fe
Content-Type: application/json
Cf-Connecting-Ip: 192.30.253.29
Cdn-Loop: cloudflare
X-Forwarded-Host: gh.pennydreadfulmagic.com

X-Forwarded-Server: gh.pennydreadfulmagic.com
Connection: Keep-Alive
Content-Length: 25300
IndexError
list index out of range
Stack Trace:

  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/discord/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/discord/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/discord/.local/lib/python3.6/site-packages/github_webhook/webhook.py", line 73, in _postreceive
    hook(data)
  File "./github_tools/__init__.py", line 48, in on_pull_request
    webhooks.check_for_changelogs(pr)
  File "./github_tools/webhooks.py", line 71, in check_for_changelogs
    lines = build_changelog(change)
  File "./github_tools/webhooks.py", line 89, in build_changelog
    oldversions[req.name] = req.specs[0][1]

Exception_hash: a3002f02109b60a0f38c2e56461fccb1a0a0b99e

Labels: github_tools; IndexError
```

**Comment by silasary** [comment] 2019-03-05 22:11
Duplicate of #5080.  Changelog generator can't handle the git hash for discord.py

**Comment by bakert** [comment] 2019-03-06 20:10
I want to fix this up in some way so it doesn't email me so reopening.

**Comment by silasary** [comment] 2019-03-06 20:52
Reopening #5080 instead

**Closed as completed by silasary** 2019-03-06 20:52 UTC
Labels: triage
